services:
  - type: web
    name: weather-mcp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/server.py
    autoDeploy: false
    envVars:
      - key: PORT
        value: 8000
      - key: WEATHER_API_KEY
        value: demo
